Models/ErrorViewModel.cs
namespace folha_de_ponto.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/FolhaPonto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
// Todos os dados referentes ao registro de ponto do funcionário
namespace folha_de_ponto.Models
{
    public class FolhaPonto
    {
        public int Id { get; set; }
        public string IdFuncionario { get; set; }
        public DateTime Data { get; set; }
    }
}

Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
// Todos os dados que se referem ao cadastro do funcionário
namespace folha_de_ponto.Models
{
    public class Funcionario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public bool Ativo { get; set; }
    }
}

Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using folha_de_ponto.Context;
using folha_de_ponto.Models;
using Microsoft.AspNetCore.Mvc;

namespace folha_de_ponto.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly PontoContext _context;

        public FuncionarioController(PontoContext context)
        {
            _context = context;
        }
        // Tela inicial para apresentar os funcionários cadastrados e opções para cadastro, edição,
        // detalhes e exclusão
        public IActionResult Index()
        {
            var funcionarios = _context.Funcionarios.ToList();
            return View(funcionarios);
        }
        // Tela de cadastro do novo funcionário
        public IActionResult Cadastrar()
        {
            return View();
        }
        // Função de inclusão do cadastro do novo funcionário fazendo a chamada da model Funcionário
        [HttpPost]
        public IActionResult Cadastrar(Funcionario funcionario)
        {
            if(ModelState.IsValid)
            {
                _context.Funcionarios.Add(funcionario);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }
        // Tela para a edição do cadastro já realizado do funcionário caso haja alguma mudança de dados do mesmo
        public IActionResult Editar(int id)
        {
            var funcionario = _context.Funcionarios.Find(id);

            if(funcionario==null)
                return RedirectToAction(nameof(Index));

            return View(funcionario);
        }
        // Função de edição do cadastro do funcionário
        [HttpPost]
        public IActionResult Editar(Funcionario funcionario)
        {
            var funcionarioBanco = _context.Funcionarios.Find(funcionario.Id);
            funcionarioBanco.Nome = funcionario.Nome;
            funcionarioBanco.Telefone = funcionario.Telefone;
            funcionarioBanco.Ativo = funcionario.Ativo;

            _context.Funcionarios.Update(funcionarioBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        // Tela de detalhes do funcionário cadastrado através do ID
        public IActionResult Detalhes(int id)
        {
            var funcionario = _context.Funcionarios.Find(id);

            if(funcionario==null)
                return RedirectToAction(nameof(Index));
            
            return View(funcionario);
        }
        // Tela de exclusão do cadastro do funcionário através do ID
        public IActionResult Deletar(int id)
        {
            var funcionario = _context.Funcionarios.Find(id);

            if(funcionario==null)
                return RedirectToAction(nameof(Index));
            
            return View(funcionario);
        }
        //  Função que realiza a exclusão do cadastro do funcionário
        [HttpPost]
        public IActionResult Deletar(Funcionario funcionario)
        {
            var funcionarioBanco = _context.Funcionarios.Find(funcionario.Id);

            _context.Funcionarios.Remove(funcionarioBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        // Tela de registro de ponto, onde são listados todos os funcionários cadastrados
        public IActionResult Ponto(int id)
        {
            var funcionarios = _context.Funcionarios.ToList();
            return View(funcionarios);
        }
        // Tela de registro de ponto, onde deve ser inserido o ID do funcionário
        public IActionResult Registrar()
        {
            return View();
        }
        // Função que realiza o registro do ponto e insere na tabela FolhasPontos
        [HttpPost]
        public IActionResult Registrar(FolhaPonto folhaPonto)
        {
            if(ModelState.IsValid)
            {
                folhaPonto.Data = DateTime.Now;
                _context.FolhasPontos.Add(folhaPonto);
                _context.SaveChanges();
                return RedirectToAction(nameof(Ponto));
            }
            return View(folhaPonto);
        }
        // Tela onde é feita a consulta de todos os pontos registrados
        public IActionResult Consultar(int idFuncionario)
        {
            var folhaPonto = _context.FolhasPontos.ToList();
            return View(folhaPonto);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using folha_de_ponto.Models;

namespace folha_de_ponto.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Funcionario/Cadastrar.cshtml
@model folha_de_ponto.Models.Funcionario

@{
    ViewData["Title"] = "Cadastrar novo funcionario";
}

<h1>Cadastrar novo funcionario</h1>

<hr/>
@* Realiza o cadastro do funcionário no sistema *@
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cadastrar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <input type="checkbox" asp-for="Ativo" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Funcionario/Consultar.cshtml
@model IEnumerable<folha_de_ponto.Models.FolhaPonto>

@{
    ViewData["Title"] = "Detalhes dos pontos";
}

<h1>Detalhes dos pontos</h1>
@* Apresenta todos os pontos registrados com o código do funcionário e o horário *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdFuncionario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.IdFuncionario)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Data)
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Ponto">Voltar</a>

Views/Funcionario/Deletar.cshtml
@model folha_de_ponto.Models.Funcionario

@{
    ViewData["Title"] = "Deletar funcionario";
}
@* Deleta o cadastro do funcionário *@
<h1 style="color: red;">Deseja realmente deletar este funcionario? Esta operação é irreversível</h1>

</hr>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ativo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ativo)
        </dt>
    </dl>
</div>

<form asp-action="Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger"/>
</form>

<br>
<a asp-action="Index">Voltar</a>

Views/Funcionario/Detalhes.cshtml
@model folha_de_ponto.Models.Funcionario

@{
    ViewData["Title"] = "Detalhes do funcionario";
}

<h1>Detalhes</h1>
@* Apresenta os detalhes do cadastro do funcionário *@
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ativo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ativo)
        </dt>
    </dl>
</div>
<a asp-action="Editar" asp-route-id="@Model.Id">Editar</a> |
<a asp-action="Index">Voltar</a>

Views/Funcionario/Editar.cshtml
@model folha_de_ponto.Models.Funcionario

@{
    ViewData["Title"] = "Editar cadastro funcionario";
}

<h1>Editar cadastro funcionário</h1>

<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <input type="checkbox" asp-for="Ativo" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Funcionario/Index.cshtml
@model IEnumerable<folha_de_ponto.Models.Funcionario>

@{
    ViewData["Title"] = "Listagem de Funcionarios";
}
@* Pagina inicial onde são listados os funcionários e possui os links para cadastrar,
   editar, detalhar e excluir. *@
<h2>Funcionários</h2>

<p>
    <a asp-action="Cadastrar">Novo Funcionário</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Ativo)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Funcionario/Ponto.cshtml
@model IEnumerable<folha_de_ponto.Models.Funcionario>

@{
    ViewData["Title"] = "Ponto";
}

<h2>Funcionários - Ponto</h2>
@* Listar os funcionários com seus respectivos códigos de cadastro *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nome)
                </td>
                <td>
                    
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Registrar">Registrar Ponto</a> |
    <a asp-action="Consultar">Consultar Pontos</a>
</div>

Views/Funcionario/Registrar.cshtml
@model folha_de_ponto.Models.FolhaPonto

@{
    ViewData["Title"] = "Registrar Ponto";
}

<h1>Registrar Ponto</h1>

<hr/>
@* Realiza o registro do ponto ao informar o código do funcionário *@
<div class="row">
    <div class="col-md-4">
        <form asp-action="Registrar">
            <div class="form-group">
                <label asp-for="IdFuncionario" class="control-label"></label>
                <input asp-for="IdFuncionario" class="form-control" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Ponto">Voltar</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Folha de Ponto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/folha_de_ponto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Folha de Ponto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Ponto">Ponto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Folha de Ponto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>